#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Philo\Blade\Blade;

$arguments = array('cwd' => FALSE, 'tmpl' => FALSE);

foreach ($argv as $arg)
{
    $e = explode("=", $arg);

    $e[0] = ltrim($e[0], '--');

    if (count($e)==2 && array_key_exists($e[0], $arguments))
    {
        $arguments[$e[0]]=$e[1];
    }
}

$cwd = $arguments['cwd'];

// include default config
$options = require 'config.php';

// if it exists, also include config from working directory
if (file_exists($cwd.'/config.php'))
{
    $custom_options = include $cwd.'/config.php';
    $options = array_merge($options, $custom_options);
}

foreach ($options['boot'] as $file)
{
    require($file);
}

$blade = new Blade($options['views'], $options['cache']);

$tmpl_name = str_replace(array('.blade.php', $options['views'].'/'), '', $arguments['tmpl']);

$variables = $options['global_variables'];
if (array_key_exists($tmpl_name, $options['template_variables']))
{
    $variables = array_merge($variables, $options['template_variables'][$tmpl_name]);
}

echo $blade->view()->make($tmpl_name, $variables);
